<?php
/**
 * @var $block \Magepow\OnestepCheckout\Block\Order\View\DeliveryTime;
 */
?>
<?php if (($deliveryTimeHtml = $block->getDeliveryTime()) || ($block->getHouseSecurityCode())): ?>
    <div class="admin__page-section-item order-delivery-time">
        <div class="admin__page-section-item-title">
            <span class="title"><?php if ($block->getDeliveryTime() && $block->getHouseSecurityCode()) {
                    echo __('Delivery Time & House Security Code');
                } else if ($block->getHouseSecurityCode()) {
                    echo __('House Security Code');
                } else if ($block->getDeliveryTime()) {
                    echo __('Delivery Time');
                } ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <?php if ($deliveryTimeHtml): ?>
                <br><strong><?php echo __('Delivery Time') ?>: </strong><span><?php echo $deliveryTimeHtml ?></span>
            <?php endif; ?>
            <?php if ($houseSecurityCodeHtml = $block->getHouseSecurityCode()): ?>
                <br><strong><?php echo __('House Security Code') ?>: </strong><span><?php echo $houseSecurityCodeHtml ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
