<?php
/**
 * @var $block \Magepow\OnestepCheckout\Block\Order\View\DeliveryTime
 */
?>
<?php if (($deliveryTimeHtml = $block->getDeliveryTime()) || ($block->getHouseSecurityCode())): ?>
    <div class="box box-order-delivery-time">
        <strong class="box-title">
            <span class="title"><?php if ($block->getDeliveryTime() && $block->getHouseSecurityCode()) {
                    echo __('Delivery Time & House Security Code');
                } else if ($block->getHouseSecurityCode()) {
                    echo __('House Security Code');
                } else if ($block->getDeliveryTime()) {
                    echo __('Delivery Time');
                } ?></span>
        </strong>
        <div class="box-delivery-time">
            <?php if ($deliveryTimeHtml): ?>
                <br><strong><?php echo __('Delivery Time') ?>: </strong><span><?php echo $deliveryTimeHtml ?></span>
            <?php endif; ?>
            <?php if ($houseSecurityCodeHtml = $block->getHouseSecurityCode()): ?>
                <br><strong><?php echo __('House Security Code') ?>: </strong><span><?php echo $houseSecurityCodeHtml ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

